server:
  port: 8081

spring:
  application:
    name: apache FOP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/apachefop
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

